export const API_CONSTANTS = {
    LOGIN_URL: "/admin/auth/login",
    CHANGE_PASSWORD: "/admin/auth/changePassword",
    ADMIN_DETAILS: "/admin/auth/getAdminProfile",
    EDIT_PROFILE_DETAILS: "/admin/auth/editProfile",
    DASHBOARD_DETAILS: "/admin/dashboard",
    FORGET_PASSWORD: "/admin/auth/forgotPassword",
    RESET_PASSWORD: "/admin/auth/resetPassword",
    USER: "/admin-user",
    TEAM_LIST: "/admin/user/get-team-members",
    USER_STATUS: "/admin-user/change-status",
    SUBSCRIPTION_PLAN_LIST: "/admin/subscriptionPlan/list",
    SUBSCRIPTION_CREATE: "/admin/subscriptionPlan/create",
    SUBSCRIPTION_UPDATE: "/admin/subscriptionPlan/update",
    SUBSCRIPTION_DELETE: "/admin/subscriptionPlan/delete",
    SUBSCRIPTION_STATUS: "/admin/subscriptionPlan/status",
    ORDER_LIST: "/admin-order",
    PINCODE: "/pincode-admin",
    CATEGORY: "/admin-category",
    BRAND: "/admin-brands",
    GET_BRAND:"/admin-brands/get-brand",
    TECH_SPECS: "/admin-tech-specs",
    PRODUCT: "/admin-products",
    
    COLOR: "/admin-color",
    PRODUCT_VARIANT: "/admin-products/details",
    WARRANTY: "/admin-product-warranty",

    ATTRIBUTE: "/admin-attribute",
    ADD_ON: "/add-addon",
    ADD_ATTRIBUTE: "/add-attribute",

    //Routes for Product Management
    PRODUCT_BRAND: "product/create/product-brand",
    PRODUCT_CATEGORY: "product/create/product-category",
    PRODUCT_ATTRIBUTE: "product/create/product-attribute",
    PRODUCT_IMAGE: "product/create/product-image",
    PRODUCT_PRICE_INVENTORY: "product/create/product-price-inventory",
    PRODUCT_MAUFACTURING_DETAIL: "product/create/product-manufacturing-detail",
    PRODUCT_SEARCH_KEYWORD: "product/create/product-search-keyword",
    PRODUCT_WARRANTY: "product/create/product-warranty",
    PRODUCT_RETURN_POLICY: "product/create/product-return-policy",
    PRODUCT_ADD_ON:"product/create/product-add-on",
    
}